import {
  existsSync,
  mkdirSync,
  readdirSync,
  statSync,
  writeFileSync
} from 'node:fs';
import path from 'node:path';

const PAGE_FILE_REGEX = /^page\.(tsx|ts|jsx|js|mdx)$/;

export interface GeneratedRoute {
  path: string;
  toolName: string;
}

export interface GenerateWebMCPRoutesOptions {
  appDir: string;
  outFile: string;
  basePath?: string;
}

function collectPageFiles(appDir: string): string[] {
  if (!existsSync(appDir)) {
    return [];
  }

  const pageFiles: string[] = [];

  const walk = (currentPath: string) => {
    for (const entry of readdirSync(currentPath)) {
      const fullPath = path.join(currentPath, entry);
      const entryStats = statSync(fullPath);

      if (entryStats.isDirectory()) {
        if (entry.startsWith('@')) {
          continue;
        }
        walk(fullPath);
        continue;
      }

      if (PAGE_FILE_REGEX.test(entry)) {
        pageFiles.push(fullPath);
      }
    }
  };

  walk(appDir);
  return pageFiles;
}

function normalizeRouteSegment(segment: string): string | null {
  if (!segment) {
    return null;
  }

  if (segment.startsWith('(') && segment.endsWith(')')) {
    return null;
  }

  if (segment.startsWith('@')) {
    return null;
  }

  return segment;
}

function joinPath(basePath: string, routePath: string): string {
  const normalizedBase = basePath.replace(/^\/+|\/+$/g, '');
  const normalizedRoute = routePath.replace(/^\/+|\/+$/g, '');

  if (!normalizedBase && !normalizedRoute) {
    return '/';
  }

  if (!normalizedBase) {
    return `/${normalizedRoute}`;
  }

  if (!normalizedRoute) {
    return `/${normalizedBase}`;
  }

  return `/${normalizedBase}/${normalizedRoute}`;
}

function toRoutePath(pageFile: string, appDir: string, basePath = ''): string {
  const relativePath = path.relative(appDir, pageFile);
  const routeDir = path.dirname(relativePath);
  const rawSegments = routeDir === '.' ? [] : routeDir.split(path.sep);

  const routeSegments = rawSegments
    .map((segment) => normalizeRouteSegment(segment))
    .filter((segment): segment is string => Boolean(segment));

  const routePath = routeSegments.length > 0 ? `/${routeSegments.join('/')}` : '/';
  return joinPath(basePath, routePath);
}

function toToolName(routePath: string): string {
  if (routePath === '/') {
    return 'navigate_to_home';
  }

  const parts = routePath
    .split('/')
    .filter(Boolean)
    .map((segment) =>
      segment
        .replace(/^\[\.\.\.(.+)\]$/, '$1')
        .replace(/^\[\[\.\.\.(.+)\]\]$/, '$1')
        .replace(/^\[(.+)\]$/, '$1')
        .replace(/[^a-zA-Z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '')
        .toLowerCase()
    )
    .filter(Boolean);

  return `navigate_to_${parts.join('_')}`;
}

function toRouteDefinitions(pageFiles: string[], appDir: string, basePath = ''): GeneratedRoute[] {
  const deduped = new Map<string, GeneratedRoute>();

  for (const pageFile of pageFiles) {
    const routePath = toRoutePath(pageFile, appDir, basePath);
    deduped.set(routePath, {
      path: routePath,
      toolName: toToolName(routePath)
    });
  }

  return [...deduped.values()].sort((a, b) => a.path.localeCompare(b.path));
}

function buildGeneratedFile(routes: GeneratedRoute[]): string {
  const serializedRoutes = JSON.stringify(routes, null, 2);

  return [
    '// This file is auto-generated by next-webmcp. Do not edit manually.',
    '',
    `export const generatedNavigationRoutes = ${serializedRoutes} as const;`,
    '',
    'export type GeneratedNavigationRoute = (typeof generatedNavigationRoutes)[number];',
    '',
    'export const generatedRoutePathMap = Object.fromEntries(',
    '  generatedNavigationRoutes.map((route) => [route.toolName, route.path])',
    ');',
    ''
  ].join('\n');
}

export function generateWebMCPRoutes({
  appDir,
  outFile,
  basePath
}: GenerateWebMCPRoutesOptions): GeneratedRoute[] {
  const pageFiles = collectPageFiles(appDir);
  const routes = toRouteDefinitions(pageFiles, appDir, basePath);

  mkdirSync(path.dirname(outFile), { recursive: true });
  writeFileSync(outFile, buildGeneratedFile(routes), 'utf8');

  return routes;
}
