import { z } from 'zod';
import { describe, expect, it } from 'vitest';

import { ToolExecutionError } from '../../src/shared/errors.js';
import { createToolContext } from '../../src/server/context.js';
import { createToolAction, executeTool } from '../../src/server/create-tool-action.js';
import { defineTool } from '../../src/server/define-tool.js';

describe('server tool execution', () => {
  it('supports top-level action execution via executeTool', async () => {
    const createTaskTool = defineTool({
      name: 'create_task',
      inputSchema: z.object({
        title: z.string(),
        priority: z.enum(['low', 'medium', 'high']).default('medium')
      }),
      outputSchema: z.object({
        id: z.string(),
        success: z.boolean()
      })
    });

    const getContext = createToolContext({
      getAuth: () => ({ userId: 'u1' }),
      createRequestId: () => 'req_1'
    });

    const result = await executeTool(
      createTaskTool,
      { title: 'ship', priority: 'high' },
      async ({ title, priority }, context) => ({
        id: `${context.auth?.userId}:${title}:${priority}`,
        success: true
      }),
      { getContext }
    );

    expect(result).toEqual({
      id: 'u1:ship:high',
      success: true
    });
  });

  it('validates input and returns typed output', async () => {
    const addTool = defineTool({
      name: 'add_numbers',
      inputSchema: z.object({ a: z.number(), b: z.number() }),
      outputSchema: z.object({ sum: z.number() })
    });

    const action = createToolAction(addTool, async ({ a, b }) => ({ sum: a + b }));

    await expect(action({ a: 2, b: 3 })).resolves.toEqual({ sum: 5 });
  });

  it('injects context generated by createToolContext', async () => {
    const whoAmITool = defineTool({
      name: 'who_am_i',
      inputSchema: z.object({ includeMetadata: z.boolean().default(false) }),
      outputSchema: z.object({
        userId: z.string(),
        requestId: z.string(),
        metadata: z.record(z.unknown()).optional()
      })
    });

    const getContext = createToolContext({
      getAuth: async () => ({ userId: 'user_123' }),
      getMetadata: async () => ({ source: 'test' }),
      createRequestId: () => 'req_test_1'
    });

    const action = createToolAction(
      whoAmITool,
      async ({ includeMetadata }, context) => ({
        userId: context.auth?.userId ?? 'anonymous',
        requestId: context.requestId,
        metadata: includeMetadata ? context.metadata : undefined
      }),
      { getContext }
    );

    await expect(action({ includeMetadata: true })).resolves.toEqual({
      userId: 'user_123',
      requestId: 'req_test_1',
      metadata: { source: 'test' }
    });
  });

  it('throws normalized errors for invalid input, handler failures, and invalid output', async () => {
    const flakyTool = defineTool({
      name: 'flaky_tool',
      inputSchema: z.object({ shouldFail: z.boolean(), mode: z.enum(['ok', 'bad-output']) }),
      outputSchema: z.object({ ok: z.boolean() })
    });

    const action = createToolAction(flakyTool, async ({ shouldFail, mode }) => {
      if (shouldFail) {
        throw new Error('Handler exploded');
      }

      if (mode === 'bad-output') {
        return { nope: true };
      }

      return { ok: true };
    });

    await expect(action({ shouldFail: false, mode: 'ok' })).resolves.toEqual({ ok: true });

    await expect(action({ shouldFail: false, mode: 'invalid-mode' as 'ok' })).rejects.toMatchObject({
      code: 'INVALID_INPUT'
    });

    await expect(action({ shouldFail: true, mode: 'ok' })).rejects.toMatchObject({
      code: 'HANDLER_ERROR',
      message: 'Handler exploded'
    });

    await expect(action({ shouldFail: false, mode: 'bad-output' })).rejects.toMatchObject({
      code: 'INVALID_OUTPUT'
    });

    await expect(action({ shouldFail: true, mode: 'ok' })).rejects.toBeInstanceOf(ToolExecutionError);
  });
});
